version: "3.8"

services:
  spa-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
      - "3001:3001"
    volumes:
      - ./db.json:/app/db.json
    restart: unless-stopped
