version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "1234:1234"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
      - /app/.parcel-cache
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend

  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./db.json:/app/db.json
    ports:
      - "3001:3001"
    command: npx json-server --host 0.0.0.0 --watch /app/db.json --port 3001
